"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Divider,
  Stack,
  Typography,
} from "@mui/material";

import DashboardPageLayout from "@/components/DashboardPageLayout";
import { downloadSharedRepositoryReportPdf, getSharedRepositoryReport } from "@/services/repositoryService";
import type { SavedRepositoryReport } from "@/types/repository";

function downloadMarkdown(report: SavedRepositoryReport) {
  const blob = new Blob([report.markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${report.repositoryFullName.replace("/", "-")}-shared-report.md`;
  anchor.click();
  URL.revokeObjectURL(url);
}

async function downloadPdf(report: SavedRepositoryReport, shareId: string) {
  const blob = await downloadSharedRepositoryReportPdf(shareId);
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${report.repositoryFullName.replace("/", "-")}-shared-report.pdf`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function SharedReportPage() {
  const params = useParams<{ shareId: string }>();
  const [report, setReport] = useState<SavedRepositoryReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    async function loadSharedReport() {
      try {
        setLoading(true);
        setErrorMessage("");
        const data = await getSharedRepositoryReport(params.shareId);
        setReport(data);
      } catch (error) {
        console.error(error);
        setErrorMessage(
          error instanceof Error ? error.message : "Failed to load shared report."
        );
      } finally {
        setLoading(false);
      }
    }

    if (params.shareId) {
      loadSharedReport();
    }
  }, [params.shareId]);

  return (
    <DashboardPageLayout
      title="Shared Repository Report"
      subtitle="A public, recruiter-friendly snapshot generated by RepoLens."
      maxWidth="md"
    >
      {errorMessage && <Alert severity="error">{errorMessage}</Alert>}

      {loading && (
        <Box sx={{ display: "flex", justifyContent: "center", py: 6 }}>
          <CircularProgress />
        </Box>
      )}

      {report && (
        <Card variant="outlined">
          <CardContent>
            <Stack spacing={2}>
              <Box>
                <Typography variant="h5" sx={{ fontWeight: "bold" }}>
                  {report.repositoryFullName}
                </Typography>
                <Typography color="text.secondary">{report.repositoryUrl}</Typography>
              </Box>

              <Stack direction="row" spacing={1} sx={{ flexWrap: "wrap" }}>
                <Chip label={`Score ${report.score}/100`} color="primary" />
                <Chip label={`Grade ${report.grade}`} variant="outlined" />
                <Chip
                  label={new Date(report.generatedAt).toLocaleString()}
                  variant="outlined"
                />
              </Stack>

              <Box sx={{ display: "flex", gap: 1, flexWrap: "wrap" }}>
                <Button variant="contained" onClick={() => downloadMarkdown(report)}>
                  Download Markdown
                </Button>
                <Button variant="contained" onClick={() => downloadPdf(report, params.shareId)}>
                  Download PDF
                </Button>
                <Button
                  variant="outlined"
                  href={report.repositoryUrl}
                  target="_blank"
                  rel="noreferrer"
                >
                  Open GitHub
                </Button>
              </Box>

              <Divider />

              <Box
                component="pre"
                sx={{
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-word",
                  bgcolor: "action.hover",
                  p: 2,
                  borderRadius: 2,
                  fontFamily: "monospace",
                  fontSize: 14,
                }}
              >
                {report.markdown}
              </Box>
            </Stack>
          </CardContent>
        </Card>
      )}
    </DashboardPageLayout>
  );
}
